author: miaobuao
title: Meo's Blog
subtitle: Hello World!
description: "Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer."
keywords: idim.cc, IT, miaobuao

logo: ./assets/favicon.ico
avatar: ./assets/avatar.jpg

theme: 111